import { useEffect, useLayoutEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { ArrowRight, Command, MagnifyingGlass, X } from '@phosphor-icons/react';
import './command.css';

export type CommandItem={id:string;label:string;meta:string;icon?:ReactNode;run:()=>void};
export function CommandPalette({open,items,onClose}:{open:boolean;items:CommandItem[];onClose:()=>void}){
  const ref=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null),list=useRef<HTMLDivElement>(null),options=useRef<(HTMLButtonElement|null)[]>([]);
  const [query,setQuery]=useState(''),[active,setActive]=useState(0);
  const visible=useMemo(()=>{const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return items.filter(item=>words.every(word=>(item.label+' '+item.meta).toLowerCase().includes(word))).slice(0,12);},[items,query]);
  useEffect(()=>{if(open){ref.current?.showModal();setQuery('');setActive(0);requestAnimationFrame(()=>input.current?.focus());}else if(ref.current?.open)ref.current.close();},[open]);
  useEffect(()=>setActive(value=>Math.min(value,Math.max(0,visible.length-1))),[visible.length]);
  useLayoutEffect(()=>{const container=list.current,node=options.current[active];if(!open||!container||!node)return;const viewport=container.getBoundingClientRect(),row=node.getBoundingClientRect();if(row.top<viewport.top)container.scrollTop-=viewport.top-row.top;else if(row.bottom>viewport.bottom)container.scrollTop+=row.bottom-viewport.bottom;},[active,open]);
  function run(item:CommandItem|undefined){if(!item)return;item.run();onClose();}
  if(!open)return null;
  return <dialog ref={ref} className="command-dialog" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label="Command palette"><div><header><MagnifyingGlass size={19}/><input ref={input} value={query} onChange={e=>{setQuery(e.target.value);setActive(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(i=>Math.min(visible.length-1,i+1));}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(0,i-1));}if(e.key==='Enter'){e.preventDefault();run(visible[active]);}}} placeholder="Type a command or find a container…" aria-label="Search commands" aria-controls="command-results" aria-activedescendant={visible[active]?`command-${visible[active].id}`:undefined}/><kbd>ESC</kbd><button onClick={onClose} aria-label="Close command palette"><X size={17}/></button></header><div ref={list} id="command-results" className="command-list" role="listbox" aria-label="Available commands">{visible.map((item,index)=><button ref={element=>{options.current[index]=element;}} id={`command-${item.id}`} key={item.id} className={index===active?'active':''} role="option" aria-selected={index===active} onPointerMove={()=>setActive(index)} onClick={()=>run(item)}><span className="command-icon">{item.icon||<Command size={17}/>}</span><span><strong>{item.label}</strong><small>{item.meta}</small></span><ArrowRight size={15}/></button>)}{visible.length===0&&<p>No matching commands.</p>}</div><footer><span><kbd>↑</kbd><kbd>↓</kbd> navigate</span><span><kbd>↵</kbd> run</span><span>GLOBAL <kbd>CTRL K</kbd></span></footer></div></dialog>;
}
